spring:
  application:
    name: limit-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/java_pro
    username: postgres
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: "/limit-service"
