version: "3.9"
name: java-pro-homework

services:
  # Тестовая база данных
  db:
    image: postgres:15
    container_name: test-db
    environment:
      POSTGRES_DB: java_pro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      TZ: Europe/Moscow
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d java_pro -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5